### ISSUE TITLE
[FEATURE] add a scroll up link

### ISSUE THREAD

**Issue by Nakamcode** [dharmelolar/technical-writing-resources#34]
This scroll up link makes navigation easy and improve UX of the repo

![captures_chrome-capture-2022-9-2 (3)](https://user-images.githubusercontent.com/89482825/193447365-be87b15a-cbb0-40c1-b985-fe62d73069eb.png)

**Comment by dharmelolar** [comment]
should I assign this issue to you?

**Comment by Csrivastava003** [comment]
I would like to work on this issue.

**Comment by Csrivastava003** [comment]
What is the expected pattern and the output expected of this feature?
If you could give a detailed description.

**Comment by dharmelolar** [comment]
@Csrivastava003 I didn't open this issue so I can't really say how this feature works. You can just look through the repo and see if there's an issue you can open

**Comment by Nakamcode** [comment]
Please assign me, I'm ready to work on this

**Comment by dharmelolar** [comment]
@Nakamcode I've assigned it to you.

**Comment by Nakamcode** [comment]
thanks, I will work on this
